name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: build the crml-compiler
      run: make distribution

    - name: upload the crml-compiler
      uses: actions/upload-artifact@v2
      with:
        name: crml-compiler-all.jar
        path: ${{github.workspace}}/build/libs/crml-compiler-all.jar
        
    - name: publish the test report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
