name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the tool
      run: make distribution

    - name: upload tool
      uses: actions/upload-artifact@v2
      with:
        name: crml-compiler-all.jar
        path: ${{github.workspace}}/build/libs/crml-compiler-all.jar
